### ISSUE TITLE
Detailed readme

### ISSUE THREAD

**Issue by Soyad-yao** [supperted825/FairMOT-X#4]
Thanks for your excellent work！And i have the same idea with you but i can't implement it，Can you provide detailed insatallation in reame file or your contact information，that's a milestone in my research. Thank you in advance！

**Comment by supperted825** [comment]
Hi @Soyad-yao,

This repo uses exactly the same dependencies as the [original FairMOT](https://github.com/ifzhang/FairMOT). Please refer to the instructions on their repo to perform the installation.

Let me know if there are any specific questions that you have.

**Comment by Soyad-yao** [comment]
> Hi @Soyad-yao,
> 
> This repo uses exactly the same dependencies as the [original FairMOT](https://github.com/ifzhang/FairMOT). Please refer to the instructions on their repo to perform the installation.
> 
> Let me know if there are any specific questions that you have.
All right，i have installed FairMOT successfully in my computer.Maybe I describe this issue not clear，the problem is  that i wonder the pretrained weights are from yolox models and  which part of the dataset of BDD100K or other.

**Comment by supperted825** [comment]
No pretrained model is used. I tried using the YOLOX models from their repo but it did not improve overall tracking performance (except for YOLOX-X). Dataset is BDD100K MOT.

Actually, these details and more can be found [here](https://github.com/supperted825/FairMOT-X#results-on-bdd100k-dataset).

**Comment by Soyad-yao** [comment]
Thanks for your quick reply and your great work again.My research will be continue because of this.I will focus on this work. @supperted825

**Comment by Soyad-yao** [comment]
@supperted825 Hello Tan, I am still confused about the dataset. I would like to confirm whether to download the whole MOT data set, because it adds up to 45G.If it is a part, please let me know. Thank you very much
![bdd100k](https://user-images.githubusercontent.com/76166614/158931847-34f14ac4-f915-4d8b-9ab0-ca6c32221ba5.PNG)

**Comment by supperted825** [comment]
Hi @Soyad-yao, I trained my models with the entire train set. But the dataset is really quite big, you may consider using a part of it since it will make training faster as well.

**Comment by sparshgarg23** [comment]
hi,could you give some suggestions on how the dataset needs to be organized like folder structure etc.As well as if there are any preprocessing steps needed to convert the data in another format.
From what i know,bdd dataset needs to be converted to another format to ensure detection/tracking can be done.

**Comment by supperted825** [comment]
Hi @sparshgarg23, please refer to https://github.com/supperted825/FairMOT-X/issues/1#issuecomment-977710712

**Comment by sparshgarg23** [comment]
thanks for replying back,because i was going through the bdd100k label which is in scalabel format .The fields associated with the label are
```
name: string (must be unique over the whole dataset!)
- url: string (relative path or URL to data file)
- videoName: string (optional)
- attributes: a dictionary of frame attributes
- intrinsics
    - focal: [x, y]
    - center: [x, y]
    - nearClip:
- extrinsics
    - location
    - rotation
- timestamp: int64 (epoch time ms)
- frameIndex: int (optional, frame index in this video)
- size:
    - width: int
    - height: int
- labels [ ]:
    - id: string
    - index: int
    - category: string (classification)
    - manualShape: boolean
    - manualAttributes: boolean
    - score: float
    - attributes: a dictionary of label attributes
    - box2d:
        - x1: float
        - y1: float
        - x2: float
        - y2: float
    - box3d:
        - alpha:
        - orientation:
        - location: ()
        - dimension: (3D point, height, width, length)
    - poly2d:
        - vertices: [][]float (list of 2-tuples [x, y])
        - types: string
        - closed: boolean
    - rle:
        - counts: str
        - size: (height, width)
    - graph: (optional)
        - nodes [ ]:
            - location: [x, y] or [x, y, z]
            - category: string
            - visibility: string (optional)
            - type: string (optional)
            - score: float (optional)
            - id: string
        - edges [ ]:
            - source: string
            - target: string
            - type: string (optional)
        - type: string (optional)
```
But  in #1  you mentioned data label needs to be in the foll format
class id, track id, normalised x, normalised y, normalised w, normalised h.

So what steps should we take to convert the bdd data in the format as mentioned in your comment,or there is no need for any  conversion.I should just download and organize it as mentioned in comment.
thanks for getting back
